### PR TITLE
Typo in readme

### PR DESCRIPTION
**Pull request by vibhavagarwal5**

### CODE REVIEW

**Comment by MrDupin** [comment]
Hello @vibhavagarwal5! I think there is [another typo](https://github.com/aimacode/aima-gsoc/pull/2/commits/36ce537e28d9a7bd0c0dcb6f0043a239c3eca05a) in the readme, which I solve with #2. Can you either close this PR, or amend the other typo too (so that only one of our PRs is needed)? Thanks.

**Comment by vibhavagarwal5** [comment]
Yeah sure... I'll do it for sure

**Comment by MrDupin** [comment]
OK, thanks.

**Comment by vibhavagarwal5** [comment]
U can merge this request now i believe.

**Comment by samuelgoto** [comment]
There are a few conflicts let. Care to resolve them?

**Pull request closed without merging**
